# Generated by Django 3.2.5 on 2021-07-24 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('genero', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
